In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [100]:
accounts = pd.read_csv('ravenstack_accounts.csv')
churn_events = pd.read_csv('ravenstack_churn_events.csv')
feature_usage = pd.read_csv('ravenstack_feature_usage.csv')
subscription = pd.read_csv('ravenstack_subscriptions.csv')
support = pd.read_csv('ravenstack_support_tickets.csv')

In [5]:
accounts.sample(10)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
409,A-4e0e85,Company_409,DevTools,US,2023-09-08,organic,Enterprise,6,False,False
175,A-ad64c6,Company_175,DevTools,UK,2024-02-23,event,Pro,12,False,False
363,A-a7bd4b,Company_363,Cybersecurity,US,2023-02-15,ads,Enterprise,5,False,False
421,A-d535f6,Company_421,DevTools,US,2024-09-03,organic,Basic,12,True,True
202,A-68f37c,Company_202,HealthTech,US,2023-07-15,ads,Basic,4,False,False
365,A-ffdfd5,Company_365,EdTech,US,2024-04-13,organic,Basic,3,False,True
63,A-9badbd,Company_63,Cybersecurity,DE,2024-06-19,ads,Enterprise,5,True,False
384,A-3b37d9,Company_384,FinTech,US,2023-01-27,event,Enterprise,23,False,False
481,A-9c18c4,Company_481,HealthTech,US,2023-07-27,ads,Pro,11,False,True
499,A-781cc0,Company_499,EdTech,US,2024-09-04,organic,Pro,12,False,False

In [6]:
accounts.shape

(500, 10)

In [7]:
accounts.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag'],
      dtype='object')

In [8]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB

In [9]:
accounts.describe()

            seats
count  500.000000
mean    20.560000
std     21.044718
min      1.000000
25%      5.000000
50%     15.000000
75%     28.000000
max    163.000000

In [10]:
accounts.duplicated().sum()

np.int64(0)

In [11]:
accounts['signup_date'] = pd.to_datetime(accounts['signup_date'])

In [12]:
accounts['industry'].unique()

array(['EdTech', 'FinTech', 'DevTools', 'HealthTech', 'Cybersecurity'],
      dtype=object)

In [13]:
accounts['country'].unique()

array(['US', 'IN', 'UK', 'CA', 'DE', 'AU', 'FR'], dtype=object)

In [14]:
accounts['referral_source'].unique()

array(['partner', 'other', 'organic', 'event', 'ads'], dtype=object)

In [15]:
accounts['plan_tier'].unique()

array(['Basic', 'Enterprise', 'Pro'], dtype=object)

In [16]:
pd.crosstab(accounts['industry'], accounts['churn_flag'], normalize = 'index')

churn_flag        False     True
industry
Cybersecurity  0.840000  0.160000
DevTools       0.690265  0.309735
EdTech         0.835443  0.164557
FinTech        0.776786  0.223214
HealthTech     0.781250  0.218750

In [17]:
pd.crosstab(accounts['country'], accounts['churn_flag'], normalize = 'index')

churn_flag     False     True
country
AU          0.875000  0.125000
CA          0.826087  0.173913
DE          0.680000  0.320000
FR          0.772727  0.227273
IN          0.795918  0.204082
UK          0.810345  0.189655
US          0.766323  0.233677

In [18]:
reference_date = accounts["signup_date"].max()
accounts["account_age_days"] = (reference_date - accounts["signup_date"]).dt.days

In [19]:
accounts["tenure_bucket"] = pd.cut(
    accounts["account_age_days"],
    bins=[0,30,90,180,365,10000],
    labels=["0-30","30-90","90-180","180-365","365+"]
)

In [20]:
accounts["signup_month"] = accounts["signup_date"].dt.month
accounts["signup_year"] = accounts["signup_date"].dt.year

In [21]:
accounts.sample(2)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,account_age_days,tenure_bucket,signup_month,signup_year
12,A-6c093d,Company_12,DevTools,US,2023-04-14,partner,Basic,7,True,False,627,365+,4,2023
171,A-9779ad,Company_171,Cybersecurity,AU,2024-03-29,event,Pro,40,True,True,277,180-365,3,2024

In [22]:
pd.crosstab(accounts['tenure_bucket'], accounts['churn_flag'], normalize = 'index')

churn_flag        False     True
tenure_bucket
0-30           0.937500  0.062500
30-90          0.825397  0.174603
90-180         0.814286  0.185714
180-365        0.780488  0.219512
365+           0.744493  0.255507

In [23]:
pd.crosstab(accounts['signup_month'], accounts['churn_flag'], normalize = 'index')

churn_flag       False     True
signup_month
1             0.787879  0.212121
2             0.645161  0.354839
3             0.808511  0.191489
4             0.783784  0.216216
5             0.770833  0.229167
6             0.735294  0.264706
7             0.850000  0.150000
8             0.864865  0.135135
9             0.708333  0.291667
10            0.725490  0.274510
11            0.807018  0.192982
12            0.864865  0.135135

In [24]:
pd.crosstab(accounts['signup_year'], accounts['churn_flag'], normalize = 'index')

churn_flag      False     True
signup_year
2023         0.744493  0.255507
2024         0.809524  0.190476

In [25]:
pd.crosstab(accounts['referral_source'], accounts['churn_flag'], normalize = 'index')

churn_flag          False     True
referral_source
ads              0.765306  0.234694
event            0.697917  0.302083
organic          0.824561  0.175439
other            0.757282  0.242718
partner          0.853933  0.146067

In [26]:
pd.crosstab(accounts['plan_tier'], accounts['churn_flag'], normalize = 'index')

churn_flag     False     True
plan_tier
Basic       0.779762  0.220238
Enterprise  0.779221  0.220779
Pro         0.780899  0.219101

In [27]:
pd.crosstab(accounts['is_trial'], accounts['churn_flag'], normalize = 'index')

churn_flag     False     True
is_trial
False       0.789082  0.210918
True        0.742268  0.257732

***Feature Engineering on Accounts df***

In [28]:
accounts.sample(2)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,account_age_days,tenure_bucket,signup_month,signup_year
208,A-508199,Company_208,FinTech,AU,2024-01-28,event,Basic,19,False,False,338,180-365,1,2024
493,A-0e966d,Company_493,FinTech,IN,2024-06-25,ads,Basic,11,False,True,189,180-365,6,2024

In [29]:
X = accounts.drop(columns = ['churn_flag'])
y = accounts['churn_flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [83]:
preprocessor = ColumnTransformer([
    ('ohe_indus_cou_rsource',OneHotEncoder(sparse_output=False, drop='first'),[2,3,5]),

    ('oe_plan_tier',OrdinalEncoder(categories=[['Basic','Pro','Enterprise']]),[6])],
    remainder='passthrough'
    )

In [31]:
pipe = Pipeline([('preprocessor', preprocessor)])

In [32]:
pipe.fit_transform(X_train)
pipe.transform(X_test)

array([[0.0, 0.0, 0.0, ..., '365+', 1, 2023],
       [0.0, 0.0, 0.0, ..., '0-30', 12, 2024],
       [0.0, 0.0, 0.0, ..., '30-90', 11, 2024],
       ...,
       [0.0, 0.0, 1.0, ..., '365+', 12, 2023],
       [0.0, 0.0, 1.0, ..., '365+', 6, 2023],
       [0.0, 0.0, 1.0, ..., '365+', 9, 2023]], dtype=object)

##Chur Events

In [54]:
churn_events.sample(2)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
148,C-a1253e,A-462d45,2024-05-17,competitor,0.0,False,False,False,missing features
25,C-8843d4,A-e51ec7,2024-01-29,support,0.0,False,False,False,missing features

In [56]:
churn_events.shape

(600, 9)

In [57]:
churn_events.columns

Index(['churn_event_id', 'account_id', 'churn_date', 'reason_code',
       'refund_amount_usd', 'preceding_upgrade_flag',
       'preceding_downgrade_flag', 'is_reactivation', 'feedback_text'],
      dtype='object')

In [58]:
churn_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    object
 1   account_id                600 non-null    object
 2   churn_date                600 non-null    object
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    object
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB

In [94]:
churn_events.sample(2)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text,feedback_provided,churn_month,churn_year,churn_day,churn_day_of_week,is_price_refunded
363,C-9d9bff,A-f5641b,2024-06-17,features,0.0,False,False,False,too expensive,1,6,2024,17,0,0
341,C-9b229e,A-249769,2024-06-12,pricing,0.0,False,False,True,too expensive,1,6,2024,12,2,0

In [98]:
churn_events['account_id'].nunique()

352

In [59]:
churn_events["feedback_provided"] = churn_events["feedback_text"].notna().astype(int)

In [62]:
churn_events["feedback_text"] = churn_events["feedback_text"].fillna("missing")

In [65]:
churn_events['churn_date'] = pd.to_datetime(churn_events['churn_date'])

In [73]:
churn_events["churn_month"] = churn_events["churn_date"].dt.month
churn_events["churn_year"] = churn_events["churn_date"].dt.year
churn_events["churn_day"] = churn_events["churn_date"].dt.day
churn_events["churn_day_of_week"] = churn_events["churn_date"].dt.dayofweek

In [75]:
churn_events.sample(3)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text,feedback_provided,churn_month,churn_year,churn_day,churn_day_of_week
130,C-23a031,A-5247b3,2024-10-16,pricing,0.00,False,False,False,missing,0,10,2024,16,2
522,C-864169,A-526d93,2024-08-05,support,6.77,False,False,False,switched to competitor,1,8,2024,5,0
40,C-762dd4,A-396e5f,2024-11-30,features,0.00,False,False,False,too expensive,1,11,2024,30,5

In [77]:
churn_events['reason_code'].unique()

array(['pricing', 'support', 'budget', 'unknown', 'features',
       'competitor'], dtype=object)

In [81]:
churn_events['is_price_refunded'] = (churn_events['refund_amount_usd'] > 0).astype(int)

In [82]:
churn_events['feedback_text'].value_counts()

feedback_text
too expensive             161
missing features          155
missing                   148
switched to competitor    136
Name: count, dtype: int64

In [90]:
preprocessor1 = ColumnTransformer(
    transformers=[
        ('ohe_reasoncode_feedbacktext',
         OneHotEncoder(sparse_output=False, drop='first'),
         [3,8])
    ],
    remainder='passthrough'
)

In [93]:
pipe = Pipeline([('preprocessor1', preprocessor1)])
pipe.fit_transform(X_train)
pipe.transform(X_test)

array([[0.0, 0.0, 0.0, ..., '365+', 1, 2023],
       [0.0, 0.0, 0.0, ..., '0-30', 12, 2024],
       [0.0, 0.0, 0.0, ..., '30-90', 11, 2024],
       ...,
       [0.0, 0.0, 0.0, ..., '365+', 12, 2023],
       [0.0, 0.0, 0.0, ..., '365+', 6, 2023],
       [0.0, 0.0, 0.0, ..., '365+', 9, 2023]], dtype=object)

##feature usage

In [101]:
feature_usage.sample(2)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
17658,U-9b80cc,S-f7b517,2024-07-29,feature_20,10,4910,0,False
5918,U-ea29a7,S-14a685,2023-02-22,feature_14,8,848,0,False

In [102]:
feature_usage.shape

(25000, 8)

In [103]:
feature_usage.columns

Index(['usage_id', 'subscription_id', 'usage_date', 'feature_name',
       'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature'],
      dtype='object')

In [104]:
feature_usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  object
 1   subscription_id      25000 non-null  object
 2   usage_date           25000 non-null  object
 3   feature_name         25000 non-null  object
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB

In [105]:
feature_usage.describe()

        usage_count  usage_duration_secs   error_count
count  25000.000000         25000.000000  25000.000000
mean      10.021000          3042.202880      0.564280
std        3.143729          2056.544615      1.012595
min        0.000000             0.000000      0.000000
25%        8.000000          1350.000000      0.000000
50%       10.000000          2760.000000      0.000000
75%       12.000000          4400.000000      1.000000
max       26.000000         12696.000000      8.000000

In [109]:
feature_usage.sample(2)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
13522,U-9d0875,S-deb65c,2024-08-18,feature_8,5,895,0,False
6315,U-e70b39,S-48c5be,2024-10-06,feature_21,15,7290,1,False

In [111]:
feature_usage['feature_name'].nunique()

40

In [112]:
feature_usage['usage_count'].nunique()

27

In [44]:
subscription.sample(2)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
4190,S-70cf3c,A-3b5cd1,2024-03-24,NaN,Pro,13,637,7644,False,False,False,False,monthly,True
2710,S-4dae4f,A-6e08f3,2024-05-09,NaN,Enterprise,20,3980,47760,False,False,False,False,monthly,True

In [45]:
subscription.shape

(5000, 14)

In [46]:
subscription.columns

Index(['subscription_id', 'account_id', 'start_date', 'end_date', 'plan_tier',
       'seats', 'mrr_amount', 'arr_amount', 'is_trial', 'upgrade_flag',
       'downgrade_flag', 'churn_flag', 'billing_frequency', 'auto_renew_flag'],
      dtype='object')

In [47]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   object
 1   account_id         5000 non-null   object
 2   start_date         5000 non-null   object
 3   end_date           486 non-null    object
 4   plan_tier          5000 non-null   object
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   object
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), int64(3), object(6)
memory usage: 376.1+ KB

In [48]:
subscription.describe()

             seats    mrr_amount     arr_amount
count  5000.000000   5000.000000    5000.000000
mean     29.852000   2267.749400   27212.992800
std      23.089771   3421.375348   41056.504178
min       1.000000      0.000000       0.000000
25%      14.000000    285.000000    3420.000000
50%      24.000000    931.000000   11172.000000
75%      40.000000   2786.000000   33432.000000
max     189.000000  33830.000000  405960.000000

In [49]:
support.sample(2)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
1711,T-8d7ff3,A-eb7fac,2023-09-15,2023-09-15 05:00:00,5.0,urgent,147,NaN,False
389,T-7b0fe1,A-716841,2023-04-03,2023-04-04 16:00:00,40.0,low,176,NaN,False

In [50]:
support.shape

(2000, 9)

In [51]:
support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   object
 1   account_id                   2000 non-null   object
 2   submitted_at                 2000 non-null   object
 3   closed_at                    2000 non-null   object
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   object
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(5)
memory usage: 127.1+ KB

In [52]:
support.describe()

       resolution_time_hours  first_response_time_minutes  satisfaction_score
count            2000.000000                  2000.000000         1175.000000
mean               35.861000                    88.480000            3.981277
std                21.138427                    51.531877            0.809646
min                 1.000000                     1.000000            3.000000
25%                17.000000                    43.000000            3.000000
50%                35.000000                    88.000000            4.000000
75%                54.000000                   131.000000            5.000000
max                72.000000                   180.000000            5.000000